[package]
name = "console"
version = "0.0.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.11"
ic-cdk = "0.11.4"
ic-cdk-macros = "0.8.1"
ic-ledger-types = "0.8.0"
serde = "1.0.190"
serde_cbor = "0.11.2"
shared = { path = "../shared" }
