name: Frontend Reproducibility

on:
  workflow_dispatch:

jobs:
  frontend-reproducibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Run reproducibility test
        id: reproducibility
        run: |
          bash .github/scripts/test-reproducibility
        shell: bash

      - name: Check script exit status
        if: steps.reproducibility.outcome == 'failure'
        run: exit 1
